# Generated by Django 3.2.8 on 2021-10-30 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviate', '0002_auto_20211030_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 12, 23, 1, 592122)),
        ),
    ]
