# Generated by Django 3.2.8 on 2021-10-30 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviate', '0003_resume_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 12, 48, 19, 396159)),
        ),
    ]
