# Generated by Django 3.2.8 on 2021-10-31 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aviate', '0004_auto_20211030_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 7, 43, 5, 224135, tzinfo=utc)),
        ),
    ]
